### ISSUE TITLE
mRNA entities give "negative substring length not allowed" error

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/tripal_dev_seed#66] opened 2018-09-27 18:19 UTC
What does this mean?!

```
PDOException: SQLSTATE[22011]: Substring error: 7 ERROR: negative substring length not allowed: SELECT featureloc_id, srcname, srcfeature_id, strand, srctypename, typename, fmin, fmax, upstream, downstream, adjfmin, adjfmax, substring(residues from (cast(adjfmin as int4) + 1) for cast((upstream + (fmax - fmin) + downstream) as int4)) as residues, genus, species FROM ( SELECT FL.featureloc_id, OF.name srcname, FL.srcfeature_id, FL.strand, OCVT.name as srctypename, SCVT.name as typename, FL.fmin, FL.fmax, OO.genus, OO.species, CASE WHEN FL.strand >= 0 THEN CASE WHEN FL.fmin - :upstream <= 0 THEN 0 ELSE FL.fmin - :upstream END WHEN FL.strand < 0 THEN CASE WHEN FL.fmin - :downstream <= 0 THEN 0 ELSE FL.fmin - :downstream END END as adjfmin, CASE WHEN FL.strand >= 0 THEN CASE WHEN FL.fmax + :downstream > OF.seqlen THEN OF.seqlen ELSE FL.fmax + :downstream END WHEN FL.strand < 0 THEN CASE WHEN FL.fmax + :upstream > OF.seqlen THEN OF.seqlen ELSE FL.fmax + :upstream END END as adjfmax, CASE WHEN FL.strand >= 0 THEN CASE WHEN FL.fmin - :upstream <= 0 THEN FL.fmin ELSE :upstream END ELSE CASE WHEN FL.fmax + :upstream > OF.seqlen THEN OF.seqlen - FL.fmax ELSE :upstream END END as upstream, CASE WHEN FL.strand >= 0 THEN CASE WHEN FL.fmax + :downstream > OF.seqlen THEN OF.seqlen - FL.fmax ELSE :downstream END ELSE CASE WHEN FL.fmin - :downstream <= 0 THEN FL.fmin ELSE :downstream END END as downstream, OF.residues FROM chado.featureloc FL INNER JOIN chado.feature SF on FL.feature_id = SF.feature_id INNER JOIN chado.cvterm SCVT on SF.type_id = SCVT.cvterm_id INNER JOIN chado.feature OF on FL.srcfeature_id = OF.feature_id INNER JOIN chado.cvterm OCVT on OF.type_id = OCVT.cvterm_id INNER JOIN chado.organism OO on OF.organism_id = OO.organism_id WHERE SF.feature_id = :feature_id and NOT (OF.residues = '' or OF.residues IS NULL)) as tbl1 ; Array ( [:upstream] => 0 [:downstream] => 0 [:feature_id] => 2316 ) in chado_query() (line 1704 of /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc).
```

**Comment by bradfordcondon** [comment] 2019-01-02 21:21
https://stackoverflow.com/questions/39154661/postgresql-negative-substring-length-not-allowed-but-no-obvious-violation-in-da
upstream and downstream values = 0 
im breaking this apart piece by piece to see if i can reproduce with manual sql.

**Comment by bradfordcondon** [comment] 2019-01-02 22:08
ok, ive confirmed the problem is isolated to the substring part of the query.


`Contig10022:3435..6667-` here are the coordinates, look resonable enough to me.

```sql
substring(residues from (cast(adjfmin as int4) + 1) for cast((upstream + (fmax - fmin) + downstream) as int4))  as residues,
```

its saying take the residues from the adjfmin to fmax-fmin, plus the up/down buffer (0 in this case).  So in short, adjfmin is less than fmax-fmin.

**Comment by bradfordcondon** [comment] 2019-01-03 18:34
resolved with newlines in the anchor sequences.  the F excelsior set has been changed, need to also update the seed script.  see #73

**Closed by bradfordcondon** 2019-01-03 18:34 UTC
Labels: bug
